# pin maps for the boards i actually own
# each pin: id, label, functions, voltage, warning

BOARDS = {
    "arduino_uno": [
        {"id": "D0",  "label": "D0",  "functions": ["GPIO", "UART_RX"],              "voltage": "5V", "warning": None},
        {"id": "D1",  "label": "D1",  "functions": ["GPIO", "UART_TX"],              "voltage": "5V", "warning": None},
        {"id": "D2",  "label": "D2",  "functions": ["GPIO", "INT0"],                 "voltage": "5V", "warning": None},
        {"id": "D3",  "label": "D3",  "functions": ["GPIO", "INT1", "PWM"],          "voltage": "5V", "warning": None},
        {"id": "D4",  "label": "D4",  "functions": ["GPIO"],                         "voltage": "5V", "warning": None},
        {"id": "D5",  "label": "D5",  "functions": ["GPIO", "PWM"],                  "voltage": "5V", "warning": None},
        {"id": "D6",  "label": "D6",  "functions": ["GPIO", "PWM"],                  "voltage": "5V", "warning": None},
        {"id": "D7",  "label": "D7",  "functions": ["GPIO"],                         "voltage": "5V", "warning": None},
        {"id": "D8",  "label": "D8",  "functions": ["GPIO"],                         "voltage": "5V", "warning": None},
        {"id": "D9",  "label": "D9",  "functions": ["GPIO", "PWM"],                  "voltage": "5V", "warning": None},
        {"id": "D10", "label": "D10", "functions": ["GPIO", "PWM", "SPI_SS"],        "voltage": "5V", "warning": None},
        {"id": "D11", "label": "D11", "functions": ["GPIO", "PWM", "SPI_MOSI"],      "voltage": "5V", "warning": None},
        {"id": "D12", "label": "D12", "functions": ["GPIO", "SPI_MISO"],             "voltage": "5V", "warning": None},
        {"id": "D13", "label": "D13", "functions": ["GPIO", "SPI_SCK", "LED"],       "voltage": "5V", "warning": None},
        {"id": "A0",  "label": "A0",  "functions": ["GPIO", "ADC"],                  "voltage": "5V", "warning": None},
        {"id": "A1",  "label": "A1",  "functions": ["GPIO", "ADC"],                  "voltage": "5V", "warning": None},
        {"id": "A2",  "label": "A2",  "functions": ["GPIO", "ADC"],                  "voltage": "5V", "warning": None},
        {"id": "A3",  "label": "A3",  "functions": ["GPIO", "ADC"],                  "voltage": "5V", "warning": None},
        {"id": "A4",  "label": "A4",  "functions": ["GPIO", "ADC", "I2C_SDA"],       "voltage": "5V", "warning": None},
        {"id": "A5",  "label": "A5",  "functions": ["GPIO", "ADC", "I2C_SCL"],       "voltage": "5V", "warning": None},
        {"id": "5V",  "label": "5V",  "functions": ["POWER"],                        "voltage": "5V", "warning": None},
        {"id": "3V3", "label": "3.3V","functions": ["POWER"],                        "voltage": "3.3V","warning": None},
        {"id": "GND", "label": "GND", "functions": ["GND"],                          "voltage": "0V", "warning": None},
        {"id": "RST", "label": "RST", "functions": ["RESET"],                        "voltage": "5V", "warning": None},
        {"id": "VIN", "label": "VIN", "functions": ["POWER_IN"],                     "voltage": "7-12V","warning": None},
    ],

    "esp32_elegoo": [
        {"id": "GPIO0",  "label": "GPIO0",  "functions": ["GPIO", "ADC2_CH1", "TOUCH1", "BOOT"],           "voltage": "3.3V", "warning": None},
        {"id": "GPIO1",  "label": "GPIO1",  "functions": ["GPIO", "UART0_TX"],                              "voltage": "3.3V", "warning": "used by USB serial"},
        {"id": "GPIO2",  "label": "GPIO2",  "functions": ["GPIO", "ADC2_CH2", "TOUCH2", "LED"],             "voltage": "3.3V", "warning": None},
        {"id": "GPIO3",  "label": "GPIO3",  "functions": ["GPIO", "UART0_RX"],                              "voltage": "3.3V", "warning": "used by USB serial"},
        {"id": "GPIO4",  "label": "GPIO4",  "functions": ["GPIO", "ADC2_CH0", "TOUCH0", "DAC1"],            "voltage": "3.3V", "warning": None},
        {"id": "GPIO5",  "label": "GPIO5",  "functions": ["GPIO", "SPI_SS", "PWM"],                         "voltage": "3.3V", "warning": None},
        {"id": "GPIO12", "label": "GPIO12", "functions": ["GPIO", "ADC2_CH5", "TOUCH5", "SPI_MISO", "PWM"],"voltage": "3.3V", "warning": None},
        {"id": "GPIO13", "label": "GPIO13", "functions": ["GPIO", "ADC2_CH4", "TOUCH4", "SPI_MOSI", "PWM"],"voltage": "3.3V", "warning": None},
        {"id": "GPIO14", "label": "GPIO14", "functions": ["GPIO", "ADC2_CH6", "TOUCH6", "SPI_CLK", "PWM"], "voltage": "3.3V", "warning": None},
        {"id": "GPIO15", "label": "GPIO15", "functions": ["GPIO", "ADC2_CH3", "TOUCH3", "SPI_SS", "PWM"],  "voltage": "3.3V", "warning": None},
        {"id": "GPIO16", "label": "GPIO16", "functions": ["GPIO", "UART2_RX", "PWM"],                       "voltage": "3.3V", "warning": None},
        {"id": "GPIO17", "label": "GPIO17", "functions": ["GPIO", "UART2_TX", "PWM"],                       "voltage": "3.3V", "warning": None},
        {"id": "GPIO18", "label": "GPIO18", "functions": ["GPIO", "SPI_CLK", "PWM"],                        "voltage": "3.3V", "warning": None},
        {"id": "GPIO19", "label": "GPIO19", "functions": ["GPIO", "SPI_MISO", "PWM"],                       "voltage": "3.3V", "warning": None},
        {"id": "GPIO21", "label": "GPIO21", "functions": ["GPIO", "I2C_SDA", "PWM"],                        "voltage": "3.3V", "warning": None},
        {"id": "GPIO22", "label": "GPIO22", "functions": ["GPIO", "I2C_SCL", "PWM"],                        "voltage": "3.3V", "warning": None},
        {"id": "GPIO23", "label": "GPIO23", "functions": ["GPIO", "SPI_MOSI", "PWM"],                       "voltage": "3.3V", "warning": None},
        {"id": "GPIO25", "label": "GPIO25", "functions": ["GPIO", "ADC2_CH8", "DAC1", "PWM"],               "voltage": "3.3V", "warning": None},
        {"id": "GPIO26", "label": "GPIO26", "functions": ["GPIO", "ADC2_CH9", "DAC2", "PWM"],               "voltage": "3.3V", "warning": None},
        {"id": "GPIO27", "label": "GPIO27", "functions": ["GPIO", "ADC2_CH7", "TOUCH7", "PWM"],             "voltage": "3.3V", "warning": None},
        {"id": "GPIO32", "label": "GPIO32", "functions": ["GPIO", "ADC1_CH4", "TOUCH9", "PWM"],             "voltage": "3.3V", "warning": None},
        {"id": "GPIO33", "label": "GPIO33", "functions": ["GPIO", "ADC1_CH5", "TOUCH8", "PWM"],             "voltage": "3.3V", "warning": None},
        {"id": "GPIO34", "label": "GPIO34", "functions": ["GPIO", "ADC1_CH6"],                              "voltage": "3.3V", "warning": "input only"},
        {"id": "GPIO35", "label": "GPIO35", "functions": ["GPIO", "ADC1_CH7"],                              "voltage": "3.3V", "warning": "input only"},
        {"id": "GPIO36", "label": "GPIO36", "functions": ["GPIO", "ADC1_CH0"],                              "voltage": "3.3V", "warning": "input only"},
        {"id": "GPIO39", "label": "GPIO39", "functions": ["GPIO", "ADC1_CH3"],                              "voltage": "3.3V", "warning": "input only"},
        {"id": "3V3",    "label": "3.3V",   "functions": ["POWER"],                                         "voltage": "3.3V", "warning": None},
        {"id": "GND",    "label": "GND",    "functions": ["GND"],                                           "voltage": "0V",   "warning": None},
        {"id": "VIN",    "label": "VIN",    "functions": ["POWER_IN"],                                      "voltage": "5V",   "warning": None},
        {"id": "EN",     "label": "EN",     "functions": ["ENABLE"],                                        "voltage": "3.3V", "warning": None},
    ],

    "stm32f401re": [
        # port a
        {"id": "PA0",  "label": "PA0",  "functions": ["GPIO", "ADC1_IN0",  "TIM2_CH1"],               "voltage": "3.3V", "warning": None},
        {"id": "PA1",  "label": "PA1",  "functions": ["GPIO", "ADC1_IN1",  "USART2_RTS"],             "voltage": "3.3V", "warning": None},
        {"id": "PA2",  "label": "PA2",  "functions": ["GPIO", "ADC1_IN2",  "USART2_TX"],              "voltage": "3.3V", "warning": "used by ST-LINK VCP"},
        {"id": "PA3",  "label": "PA3",  "functions": ["GPIO", "ADC1_IN3",  "USART2_RX"],              "voltage": "3.3V", "warning": "used by ST-LINK VCP"},
        {"id": "PA4",  "label": "PA4",  "functions": ["GPIO", "ADC1_IN4",  "SPI1_NSS", "DAC1"],       "voltage": "3.3V", "warning": None},
        {"id": "PA5",  "label": "PA5",  "functions": ["GPIO", "ADC1_IN5",  "SPI1_SCK", "LD2"],        "voltage": "3.3V", "warning": "onboard LD2 LED"},
        {"id": "PA6",  "label": "PA6",  "functions": ["GPIO", "ADC1_IN6",  "SPI1_MISO", "TIM3_CH1"],  "voltage": "3.3V", "warning": None},
        {"id": "PA7",  "label": "PA7",  "functions": ["GPIO", "ADC1_IN7",  "SPI1_MOSI", "TIM3_CH2"],  "voltage": "3.3V", "warning": None},
        {"id": "PA8",  "label": "PA8",  "functions": ["GPIO", "I2C3_SCL",  "TIM1_CH1", "MCO1"],       "voltage": "3.3V", "warning": None},
        {"id": "PA9",  "label": "PA9",  "functions": ["GPIO", "USART1_TX", "TIM1_CH2"],               "voltage": "3.3V", "warning": None},
        {"id": "PA10", "label": "PA10", "functions": ["GPIO", "USART1_RX", "TIM1_CH3"],               "voltage": "3.3V", "warning": None},
        {"id": "PA11", "label": "PA11", "functions": ["GPIO", "USART1_CTS", "TIM1_CH4"],              "voltage": "3.3V", "warning": None},
        {"id": "PA12", "label": "PA12", "functions": ["GPIO", "USART1_RTS"],                          "voltage": "3.3V", "warning": None},
        {"id": "PA13", "label": "PA13", "functions": ["GPIO", "SWDIO"],                               "voltage": "3.3V", "warning": "SWD debug pin"},
        {"id": "PA14", "label": "PA14", "functions": ["GPIO", "SWCLK"],                               "voltage": "3.3V", "warning": "SWD debug pin"},
        {"id": "PA15", "label": "PA15", "functions": ["GPIO", "SPI1_NSS_AF", "TIM2_CH1_ETR"],         "voltage": "3.3V", "warning": None},
        # port b
        {"id": "PB0",  "label": "PB0",  "functions": ["GPIO", "ADC1_IN8",  "TIM3_CH3"],               "voltage": "3.3V", "warning": None},
        {"id": "PB1",  "label": "PB1",  "functions": ["GPIO", "ADC1_IN9",  "TIM3_CH4"],               "voltage": "3.3V", "warning": None},
        {"id": "PB2",  "label": "PB2",  "functions": ["GPIO", "BOOT1"],                               "voltage": "3.3V", "warning": None},
        {"id": "PB3",  "label": "PB3",  "functions": ["GPIO", "SPI1_SCK_AF", "I2C2_SDA_AF"],          "voltage": "3.3V", "warning": None},
        {"id": "PB4",  "label": "PB4",  "functions": ["GPIO", "SPI1_MISO_AF", "I2C3_SDA"],            "voltage": "3.3V", "warning": None},
        {"id": "PB5",  "label": "PB5",  "functions": ["GPIO", "SPI1_MOSI_AF", "I2C1_SMBA"],           "voltage": "3.3V", "warning": None},
        {"id": "PB6",  "label": "PB6",  "functions": ["GPIO", "I2C1_SCL", "USART1_TX_AF"],            "voltage": "3.3V", "warning": None},
        {"id": "PB7",  "label": "PB7",  "functions": ["GPIO", "I2C1_SDA", "USART1_RX_AF"],            "voltage": "3.3V", "warning": None},
        {"id": "PB8",  "label": "PB8",  "functions": ["GPIO", "I2C1_SCL_AF", "TIM4_CH3"],             "voltage": "3.3V", "warning": None},
        {"id": "PB9",  "label": "PB9",  "functions": ["GPIO", "I2C1_SDA_AF", "TIM4_CH4"],             "voltage": "3.3V", "warning": None},
        {"id": "PB10", "label": "PB10", "functions": ["GPIO", "I2C2_SCL", "SPI2_SCK"],                "voltage": "3.3V", "warning": None},
        {"id": "PB12", "label": "PB12", "functions": ["GPIO", "SPI2_NSS"],                            "voltage": "3.3V", "warning": None},
        {"id": "PB13", "label": "PB13", "functions": ["GPIO", "SPI2_SCK_AF"],                         "voltage": "3.3V", "warning": None},
        {"id": "PB14", "label": "PB14", "functions": ["GPIO", "SPI2_MISO"],                           "voltage": "3.3V", "warning": None},
        {"id": "PB15", "label": "PB15", "functions": ["GPIO", "SPI2_MOSI"],                           "voltage": "3.3V", "warning": None},
        # port c
        {"id": "PC0",  "label": "PC0",  "functions": ["GPIO", "ADC1_IN10"],                           "voltage": "3.3V", "warning": None},
        {"id": "PC1",  "label": "PC1",  "functions": ["GPIO", "ADC1_IN11"],                           "voltage": "3.3V", "warning": None},
        {"id": "PC2",  "label": "PC2",  "functions": ["GPIO", "ADC1_IN12", "SPI2_MISO_AF"],           "voltage": "3.3V", "warning": None},
        {"id": "PC3",  "label": "PC3",  "functions": ["GPIO", "ADC1_IN13", "SPI2_MOSI_AF"],           "voltage": "3.3V", "warning": None},
        {"id": "PC4",  "label": "PC4",  "functions": ["GPIO", "ADC1_IN14"],                           "voltage": "3.3V", "warning": None},
        {"id": "PC5",  "label": "PC5",  "functions": ["GPIO", "ADC1_IN15"],                           "voltage": "3.3V", "warning": None},
        {"id": "PC13", "label": "PC13", "functions": ["GPIO", "B1_USER"],                             "voltage": "3.3V", "warning": "onboard user button"},
        {"id": "PC14", "label": "PC14", "functions": ["GPIO", "OSC32_IN"],                            "voltage": "3.3V", "warning": None},
        {"id": "PC15", "label": "PC15", "functions": ["GPIO", "OSC32_OUT"],                           "voltage": "3.3V", "warning": None},
        # power
        {"id": "3V3",  "label": "3V3",  "functions": ["POWER"],                                       "voltage": "3.3V", "warning": None},
        {"id": "GND",  "label": "GND",  "functions": ["GND"],                                         "voltage": "0V",   "warning": None},
        {"id": "5V",   "label": "5V",   "functions": ["POWER_IN"],                                    "voltage": "5V",   "warning": None},
        {"id": "NRST", "label": "NRST", "functions": ["RESET"],                                       "voltage": "3.3V", "warning": None},
        {"id": "VBAT", "label": "VBAT", "functions": ["POWER_BACKUP"],                                "voltage": "3.3V", "warning": None},
    ],
}
